192.168.176.1version: '3.8'

services:

  # suap database service
  suapdb:
    hostname: 'suapdb'
    ports:
      - "5434:5432"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydb
    volumes:
      - postgres:/var/lib/postgresql/data
    image: postgres:13-alpine

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_DEFAULT_PASSWORD:-admin}'
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  # #suap service
  # suap:
  #   hostname: 'suap'
  #   volumes:
  #     - .:/suap:rw
  #   ports:
  #     - "8005:8000"
  #   depends_on: 'suapdb'


networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:172.17.0.1/
